apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website-api
  template:
    metadata:
      labels:
        app: personal-website-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: personal-website-api
        image: benldouthwaite/base-api:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: personal-website-api
spec:
  selector:
    app: personal-website-api
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP